# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_cppinterface_rcpp_hello_world`)
}

R_getMaxMin <- function(x, choice) {
    .Call(`_cppinterface_R_getMaxMin`, x, choice)
}

Rsort <- function(x, order) {
    .Call(`_cppinterface_Rsort`, x, order)
}

